### ISSUE TITLE
Non-standard qSet data comes through in DevMateria but filtered out in actual Materia

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Materia#856]
With a demo.yaml example of:

```

---
name: Radar Grapher
qset:
  version: 1
  data:
    items:
      -
        materiaType: question
        id: null
        type: MC
        label: U
        min: Min
        max: Max
        questions:
          -
            text: How do you feel about U?
        answers:
          -
            text: '[No Answer]'
            value: 0
```

Inside DevMateria the exact same object comes through. However in docker Materia the `label`, `min` and `max` attributes are missing as they get filtered out. Putting them inside an `options` object works. Is this expected behavior? If so, is it possible to mimic this in DevMateria?
